python: can't open file 'detection/run_detector.py': [Errno 2] No such file or directory
python: can't open file 'detection/run_detector.py': [Errno 2] No such file or directory
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.0+cu121
Sending model to GPU
Loaded model in 2.44 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.36 seconds, std dev is not available
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.0+cu121
Sending model to GPU
Loaded model in 2.46 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
100%|██████████| 1/1 [00:00<00:00,  3.15it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.32 seconds, std dev is not available
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.0+cu121
Sending model to GPU
Loaded model in 2.44 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
100%|██████████| 1/1 [00:00<00:00,  3.09it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.32 seconds, std dev is not available
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils.path_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 48, in <module>
    import humanfriendly
ModuleNotFoundError: No module named 'humanfriendly'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Collecting ultralytics
  Downloading ultralytics-8.1.19-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.3.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (3.7.1)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Downloading opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torch>=1.8.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torchvision>=0.9.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.11.2)
Requirement already satisfied: tqdm>=4.64.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (4.65.0)
Requirement already satisfied: psutil in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (5.9.8)
Collecting py-cpuinfo (from ultralytics)
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
Collecting thop>=0.1.1 (from ultralytics)
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pandas>=1.1.4 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.0.1)
Requirement already satisfied: seaborn>=0.11.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (6.1.2)
Requirement already satisfied: pytz>=2020.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2024.2.2)
Requirement already satisfied: typing_extensions in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from torch>=1.8.0->ultralytics) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->ultralytics) (3.17.0)
Requirement already satisfied: six>=1.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Downloading ultralytics-8.1.19-py3-none-any.whl (716 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.2/716.2 kB 17.3 MB/s eta 0:00:00
Downloading opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 54.8 MB/s eta 0:00:00
Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Installing collected packages: py-cpuinfo, opencv-python, thop, ultralytics
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.5.5
ERROR: Cannot uninstall opencv-python 4.5.5, RECORD file not found. Hint: The package was installed by conda.
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 39, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 85, in <module>
    from utils.general import non_max_suppression, xyxy2xywh # noqa
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 44, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 676, in <module>
    main()
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 664, in main
    load_and_run_detector(model_file=args.detector_file,
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 371, in load_and_run_detector
    detector = load_detector(model_file)
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 341, in load_detector
    from detection.pytorch_detector import PTDetector
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 96, in <module>
    raise ModuleNotFoundError('Could not import YOLOv5 functions.')
ModuleNotFoundError: Could not import YOLOv5 functions.
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Collecting ultralytics
  Using cached ultralytics-8.1.19-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: matplotlib>=3.3.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (3.7.1)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torch>=1.8.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torchvision>=0.9.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.11.2)
Requirement already satisfied: tqdm>=4.64.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (4.65.0)
Requirement already satisfied: psutil in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (5.9.8)
Requirement already satisfied: py-cpuinfo in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.0.0)
Collecting thop>=0.1.1 (from ultralytics)
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pandas>=1.1.4 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.0.1)
Requirement already satisfied: seaborn>=0.11.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (6.1.2)
Requirement already satisfied: pytz>=2020.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2024.2.2)
Requirement already satisfied: typing_extensions in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from torch>=1.8.0->ultralytics) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->ultralytics) (3.17.0)
Requirement already satisfied: six>=1.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Using cached ultralytics-8.1.19-py3-none-any.whl (716 kB)
Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Installing collected packages: opencv-python, thop, ultralytics
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.5.5
ERROR: Cannot uninstall opencv-python 4.5.5, RECORD file not found. Hint: The package was installed by conda.
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 39, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 85, in <module>
    from utils.general import non_max_suppression, xyxy2xywh # noqa
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 44, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 676, in <module>
    main()
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 664, in main
    load_and_run_detector(model_file=args.detector_file,
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 371, in load_and_run_detector
    detector = load_detector(model_file)
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 341, in load_detector
    from detection.pytorch_detector import PTDetector
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 96, in <module>
    raise ModuleNotFoundError('Could not import YOLOv5 functions.')
ModuleNotFoundError: Could not import YOLOv5 functions.
Collecting ultralytics
  Downloading ultralytics-8.1.19-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.3.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (3.7.1)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torch>=1.8.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torchvision>=0.9.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.11.2)
Requirement already satisfied: tqdm>=4.64.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (4.65.0)
Requirement already satisfied: psutil in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (5.9.8)
Requirement already satisfied: py-cpuinfo in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.0.0)
Collecting thop>=0.1.1 (from ultralytics)
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pandas>=1.1.4 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.0.1)
Requirement already satisfied: seaborn>=0.11.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (6.1.2)
Requirement already satisfied: pytz>=2020.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2024.2.2)
Requirement already satisfied: typing_extensions in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from torch>=1.8.0->ultralytics) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->ultralytics) (3.17.0)
Requirement already satisfied: six>=1.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Downloading ultralytics-8.1.19-py3-none-any.whl (716 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.2/716.2 kB 17.2 MB/s eta 0:00:00
Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Installing collected packages: opencv-python, thop, ultralytics
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.5.5
ERROR: Cannot uninstall opencv-python 4.5.5, RECORD file not found. Hint: The package was installed by conda.
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 39, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 85, in <module>
    from utils.general import non_max_suppression, xyxy2xywh # noqa
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 44, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 676, in <module>
    main()
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 664, in main
    load_and_run_detector(model_file=args.detector_file,
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 371, in load_and_run_detector
    detector = load_detector(model_file)
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 341, in load_detector
    from detection.pytorch_detector import PTDetector
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 96, in <module>
    raise ModuleNotFoundError('Could not import YOLOv5 functions.')
ModuleNotFoundError: Could not import YOLOv5 functions.
Collecting ultralytics
  Using cached ultralytics-8.1.19-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: matplotlib>=3.3.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (3.7.1)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torch>=1.8.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (1.10.1)
Requirement already satisfied: torchvision>=0.9.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.11.2)
Requirement already satisfied: tqdm>=4.64.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (4.65.0)
Requirement already satisfied: psutil in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (5.9.8)
Requirement already satisfied: py-cpuinfo in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (9.0.0)
Collecting thop>=0.1.1 (from ultralytics)
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pandas>=1.1.4 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (2.0.1)
Requirement already satisfied: seaborn>=0.11.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from ultralytics) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from matplotlib>=3.3.0->ultralytics) (6.1.2)
Requirement already satisfied: pytz>=2020.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from requests>=2.23.0->ultralytics) (2024.2.2)
Requirement already satisfied: typing_extensions in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from torch>=1.8.0->ultralytics) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->ultralytics) (3.17.0)
Requirement already satisfied: six>=1.5 in /shared/land_bridge/miniforge3/envs/cameratraps-detector/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Using cached ultralytics-8.1.19-py3-none-any.whl (716 kB)
Using cached opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Installing collected packages: opencv-python, thop, ultralytics
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.5.5
ERROR: Cannot uninstall opencv-python 4.5.5, RECORD file not found. Hint: The package was installed by conda.
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 39, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 85, in <module>
    from utils.general import non_max_suppression, xyxy2xywh # noqa
  File "/shared/land_bridge/MegaDetector_App/yolov5/utils/general.py", line 44, in <module>
    import ultralytics
ModuleNotFoundError: No module named 'ultralytics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 676, in <module>
    main()
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 664, in main
    load_and_run_detector(model_file=args.detector_file,
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 371, in load_and_run_detector
    detector = load_detector(model_file)
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 341, in load_detector
    from detection.pytorch_detector import PTDetector
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/pytorch_detector.py", line 96, in <module>
    raise ModuleNotFoundError('Could not import YOLOv5 functions.')
ModuleNotFoundError: Could not import YOLOv5 functions.
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 2.45 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
100%|██████████| 1/1 [00:00<00:00,  3.08it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.32 seconds, std dev is not available
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 2.46 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.33 seconds, std dev is not available
Downloading model MDV5A
Downloading file md_v5a.0.0.pt to /tmp/megadetector_models/md_v5a.0.0.pt...done, 280766885 bytes.
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 3 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.35 seconds, std dev is not available
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Traceback (most recent call last):
  File "/shared/land_bridge/MegaDetector_App/MegaDetector/detection/run_detector.py", line 51, in <module>
    import md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 2.41 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
On average, for each image,
- loading took 0 seconds, std dev is not available
- inference took 0.31 seconds, std dev is not available
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 8.16 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
On average, for each image,
- loading took 0.01 seconds, std dev is not available
- inference took 0.93 seconds, std dev is not available
Downloading model MDV5A
Bypassing download of already-downloaded file md_v5a.0.0.pt
Running detector on 1 images...
PyTorch reports 1 available CUDA devices
GPU available: True
Fusing layers... 
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Imported YOLOv5 as utils.*
Using PyTorch version 2.2.1+cu121
Sending model to GPU
Loaded model in 7.33 seconds

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
On average, for each image,
- loading took 0.01 seconds, std dev is not available
- inference took 0.9 seconds, std dev is not available
